#!/bin/bash
cd ~/Documents/
git clone https://github.com/andrey99429/Sputnik_IDE.git

if [ -d Sputnik_IDE/ ]; then
cd Sputnik_IDE/

pip install virtualenv
python3 -m venv venv
source venv/bin/activate

pip install --upgrade pip
pip install -r requirements.txt

./runserver

fi